FROM ubuntu:jammy
RUN apt-get update && apt-get install -y git curl
RUN curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh > mambaforge.sh && \
    bash mambaforge.sh -b -p /opt/conda && \
    export PATH=/opt/conda/bin:$PATH && \
    mamba install scikit-learn && \
    mamba install IPython && \
    pip install riverapi && \
    pip install river
ENV PATH=/opt/conda/bin:$PATH
