name: build lammps-stream-ml

on:
  pull_request: []
  push:
    branches:
    - main

jobs:
  build:
    permissions:
      packages: write

    runs-on: ubuntu-latest
    name: Build
    strategy:
      matrix:
        container: [["Dockerfile.client", "client"], ["Dockerfile", "server"]]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Container
      run: docker build -f ${{ matrix.container[0] }} -t ghcr.io/converged-computing/lammps-stream-ml:${{ matrix.container[1] }} .

    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      if: (github.event_name != 'pull_request')
      run: docker push ghcr.io/converged-computing/lammps-stream-ml:${{ matrix.container[1] }}
